name: Spotify Playlist Cleanup and Curator
on:
  schedule:
    # Defined timed cron workflows
    - cron: "0 16 * * *" # 08 AM PST / 09 AM PDT
    - cron: "0 18 * * *" # 10 AM PST / 11 AM PDT
    - cron: "0 20 * * *" # 12 PM PST / 01 PM PDT
    - cron: "0 22 * * *" # 02 PM PST / 03 PM PDT
    - cron: "0 00 * * *" # 04 pm PST / 05 PM PDT
    - cron: "0 02 * * *" # 06 PM PST / 07 PM PDT
    - cron: "0 04 * * *" # 08 PM PST / 09 PM PDT
    - cron: "0 10 * * *" # 03 AM PST / 04 AM PDT
  workflow_dispatch: # Allow manual trigger
permissions:
  contents: write 
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  run-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run cleanup script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          MONITORED_PLAYLISTS: ${{ secrets.MONITORED_PLAYLISTS }}
          ARCHIVE_PLAYLISTS: ${{ secrets.ARCHIVE_PLAYLISTS }}
          TARGET_PLAYLIST_ID: ${{ secrets.TARGET_PLAYLIST_ID }}
          CLEAN_PLAYLIST_ID: ${{ secrets.CLEAN_PLAYLIST_ID }}
          CAR_PLAYLIST_ALL_ID: ${{ secrets.CAR_PLAYLIST_ALL_ID }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          RUN_MODE: once
        run: node index.js
      - name: Commit and push all changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add history.json data/albums_by_year_63-25_api.json data/artistDisc.json data/smoothJazz.json data/billboardHot100.json data/sourceIndex.json data/1080albums.json data/rockNRollHallofFame.json data/editorsChoiceAlbums.json data/festivals.json data/artistTop10.json data/spotifyPlaylists.json
          git diff --staged --quiet || git commit -m "Update playlist state and data [skip ci]"
          git push
